config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#new"
  post 'home/create', to: 'home#create', as: 'create_event'
  post 'events/create_event', to: 'events#create_event'
  post 'emails/create', to: 'emails#create', as: 'send_email'
  resources :admin
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/campaign.rb
class Campaign < ApplicationRecord
end

app/models/email.rb
class Email < ApplicationRecord
end

app/models/event_a.rb
class EventA < MainEvent
end

app/models/event_b.rb
class EventB < MainEvent
end

app/models/main_event.rb
class MainEvent < ApplicationRecord
end

app/models/message.rb
class Message < ApplicationRecord
end

app/models/template.rb
class Template < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum role: {user: 0, admin: 1}
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:edit, :update, :destroy]
  before_action :authorize_admin!
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to admin_index_path, notice: 'User created'
    else
      redirect_to admin_index_path, alert: 'Unable to create user'
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to admin_index_path, notice: 'User updated'
    else
      redirect_to admin_index_path, alert: 'Unable to update user'
    end
  end

  def destroy
    if @user.destroy
      redirect_to admin_index_path, notice: 'User deleted'
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :role)
  end

  def authorize_admin!
    redirect_to root_path, alert: 'Access Denied' unless current_user.admin?
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/emails_controller.rb
class EmailsController < ApplicationController
  skip_before_action :verify_authenticity_token

  def create
    @email = Email.new(email_params)
    if @email.save
      EventMailer.with(user: @email).welcome_email.deliver_later
    end
  end

  private

  def email_params
    params.require(:email).permit(:campaign_id, :recipient_email, :recipient_user_id, data_field: {}, mata_data: {})
  end
end

app/controllers/events_controller.rb
require 'uri'
require 'net/http'
class EventsController < ApplicationController
  skip_before_action :verify_authenticity_token
  def create_event
    case event_params[:event_name]
    when 'Event A'
      @event = EventA.new(event_params)
    when 'Event B'
      @event = EventB.new(event_params)
    else
      return render json: { event: "Event type is not valid"}, status: :unprocessable_entity
    end
    if @event.save
      if @event.type == 'EventB'
        uri = URI('http://localhost:3000/emails/create')
        http = Net::HTTP.new(uri.host, uri.port)
        
        req = Net::HTTP::Post.new(uri.path, {'Content-Type' => 'application/json'})
        req.body = {
          email: {
            campaign_id: @event.campaign_id,
            recipient_email: @event.email,
            recipient_user_id: @event.user_id,
            data_field: {},
            mata_data: {}
          }
        }.to_json
        response = http.request(req)
      end
      render json: { event: "#{@event.event_name} created successfully"}, status: :ok
    end
  end

  private

  def event_params
    params.require(:event).permit(:email, :user_id, :campaign_id, :message_id, :event_name, :template_id, :created_by,  data_field: {})
  end
end

app/controllers/home_controller.rb
require 'uri'
require 'net/http'
class HomeController < ApplicationController
  before_action :authenticate_user!

  def new
    @users = User.where(role: 'user').map {|u| [u.email, u.id]}
    @message = Message.all.map {|u| [u.name, u.id]}
    @campaign = Campaign.all.map {|u| [u.name, u.id]}
    @template = Template.all.map {|u| [u.name, u.id]}
    @event = MainEvent.new
  end

  def create
    uri = URI('http://localhost:3000/events/create_event')
    http = Net::HTTP.new(uri.host, uri.port)
    
    req = Net::HTTP::Post.new(uri.path, {'Content-Type' => 'application/json'})
    req.body = {
      event: {
        email: User.find(params[:main_event][:user_id]).email,
        user_id: params[:main_event][:user_id],
        data_field: {},
        campaign_id: params[:main_event][:campaign_id],
        template_id: params[:main_event][:template_id],
        message_id: params[:main_event][:campaign_id],
        event_name: params[:commit],
        created_by: current_user.id
      }
    }.to_json
    response = http.request(req)
    body = JSON.parse(response.body)
    if response.code == "200"
      redirect_to root_path, notice: "#{body["event"]}"
    else
      redirect_to root_path, alert: 'Unable to create event'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/edit.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-lg-8 mx-auto">
      <div class='card mt-4'>
        <div class="card-header text-center">
          <h4 class='text-primary'>Update User</h4>
        </div>
        <%= form_with model: @user, url: admin_path, method: :patch do |form| %>
          <div class="card-body">
            <div class="form-group">
              <label class="mb-2 mt-3">
                Email
                <span class="text-danger">*</span>
              </label>
              <%= form.email_field :email, class: "form-control" %>
            </div>
            <div class="form-group">
              <label class="mb-2 mt-3">
                Role
                <span class="text-danger">*</span>
              </label>
              <%= form.select :role, options_for_select(User.roles.keys.map {|w| [w.humanize, w]}, selected: form.object.role), {prompt: 'Select role'}, class: "form-select" %>  
            </div>
          </div>
          <div class="card-footer text-center">
            <%= form.submit "Save Changes", class: "btn btn-primary" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-lg-8 mx-auto">
      <div class='card mt-4'>
        <div class="card-header">
          <div class="row">
            <div class="col-lg-6">
              <h4 class='text-primary'>Users Listing</h4>
            </div>
            <div class="col-lg-6 text-end">
              <%= link_to "Create New User", new_admin_path  %>
            </div>
          </div>
        </div>
        <div class="card-body">
          <table class="table">
            <thead>
              <tr>
                <th scope="col">Email</th>
                <th scope="col">Role</th>
                <th scope="col">Actions</th>
              </tr>
            </thead>
            <tbody>
            <% @users.each do |user| %>
              <tr>
                <td><%= user.email %></td>
                <td><%= user.role.titleize %></td>
                <td>
                  <span><%= link_to "Edit", edit_admin_path(user), class: 'btn btn-primary' %></span>
                  <span><%= link_to "Delete", admin_path(user), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: 'btn btn-danger' %></span></td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/new.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-lg-8 mx-auto">
      <div class='card mt-4'>
        <div class="card-header text-center">
          <h4 class='text-primary'>Create New User</h4>
        </div>
        <%= form_with model: @user, url: "/admin", method: :post do |form| %>
          <div class="card-body">
            <div class="form-group">
              <label class="mb-2 mt-3">
                Email
                <span class="text-danger">*</span>
              </label>
              <%= form.email_field :email, class: "form-control" %>
            </div>
            <div class="form-group">
              <label class="mb-2 mt-3">
                Role
                <span class="text-danger">*</span>
              </label>
              <%= form.select :role, options_for_select(User.roles.keys.map {|w| [w.humanize, w]}), {prompt: 'Select role'}, class: "form-select"  %>
            </div>
            <div class="form-group row">
              <div class="col-lg-6">
                <label class="mb-2 mt-3">
                  Password
                  <span class="text-danger">*</span>
                </label>
                <%= form.password_field :password, class: "form-control" %>
              </div>
              <div class="col-lg-6">
                <label class="mb-2 mt-3">
                  Confirm Password
                  <span class="text-danger">*</span>
                </label>
                <%= form.password_field :password_confirmation, class: "form-control" %>
              </div>
            </div>
          </div>
          <div class="card-footer text-center">
            <%= form.submit "Save New User", class: "btn btn-primary" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/home/_form.html.erb
<%= form_with model: @event, url: create_event_path, method: :post do |form| %>
  <div class='card-body'>
    <div class='row'>
      <div class="form-group mb-2">
        <div class='mb-2'>
          <label>User<span class="text-danger">*</span></label>
        </div>
          <% #form.collection_select :user_ids, User.all, :id, :email, { include_blank: "Please select"}, { multiple: true } %>
          <%= form.select :user_id, options_for_select(@users), {prompt: 'Select user'}, required: true, class: "form-select"%>
      </div>
      <div class="form-group">
        <label class="mb-2 mt-3">
          Campaign
          <span class="text-danger">*</span>
        </label>
        <%= form.select :campaign_id, options_for_select(@campaign), {prompt: 'Select campaign'}, required: true, class: "form-select"%>
      </div>
      <div class="form-group">
        <label class="mb-2 mt-3">
          Template
          <span class="text-danger">*</span>
        </label>
        <%= form.select :template_id, options_for_select(@template), {prompt: 'Select template'}, required: true, class: "form-select"%>
      </div>
      <div class="form-group mb-4">
        <label class="mb-2 mt-3">
          Message
          <span class="text-danger">*</span>
        </label>
        <%= form.select :message_id, options_for_select(@message), {prompt: 'Select message'}, required: true, class: "form-select"%>
      </div>
      <div class='col-lg-6'>
        <div class='d-flex justify-content-center'>
          <%= form.submit "Event A", class: "btn btn-primary" %>
        </div>
      </div>
      <div class='col-lg-6'>
        <div class='d-flex justify-content-center'>
          <%= form.submit "Event B", class: 'btn btn-primary' %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/home/new.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-lg-6 mx-auto">
      <% if current_user.admin? %>
        <% if flash.any? %>
          <div class='mt-2'>
            <div class="alert alert-primary" role="alert">
              <% flash.each do |type, msg| %>
                <div>
                  <%= msg %>
                </div>
              <% end %>
            </div>
          </div>
        <% end %>
        <div class='card mt-3'>
          <div class='card-header text-center'>
            <h5 class='text-primary'>Event</h5>
          </div>
          <%= render 'form' %>
          <div class='card-footer'>
            <div class='row'>
              <div class='col-lg-6'>
                <small class='text-muted'><%= current_user.email %></small>
              </div>
              <div class='col-lg-6 text-end'>
                <small><%= link_to "Sign Out", destroy_user_session_path, data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to sign out?"} %></small>
              </div>
            </div>
          </div>
        </div>
      <% else %>
        <h3 class="mt-4">Nothing is here....!!!!</h3>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container-fluid">
    <%= link_to "Event", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if user_signed_in? %>
          <% if current_user.admin? %>
            <li class="nav-item">
              <%= link_to "User Management", admin_index_path, class: "nav-link active" %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Log Out", destroy_user_session_path, data: {turbo_method: :delete, turbo_confirm: "Are you sure you want to sign out?" }, class: "nav-link active" %>
            </li>
          <% end %>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Event</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class='container-fluid'>
      <div class='row'>
        <div class='col-lg-8 mx-auto'>
          <%= render 'layouts/navbar' %>
        </div>
        <div class='col-lg-8 mx-auto'>
          <%= yield %>
        </div>
    </div>
  </body>
</html>